spring.application.name=PractFirst

spring.datasource.url=jdbc:mysql://localhost:3306/alpha
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl.auto=update
spring.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect	
